services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    restart: unless-stopped
    command: --config /etc/livekit.yaml
    volumes:
      - ../livekit.yaml:/etc/livekit.yaml:ro
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50050:50000-50050/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.livekit-ws.rule=Host(`${DOMAIN_LIVEKIT}`) && (PathPrefix(`/rtc`) || PathPrefix(`/twirp`))"
      - "traefik.http.routers.livekit-ws.entrypoints=web,websecure"
      - "traefik.http.routers.livekit-ws.service=livekit-ws-service"
      - "traefik.http.routers.livekit-ws.tls=false"
      - "traefik.http.services.livekit-ws-service.loadbalancer.server.port=7880"
    networks:
      - traefik-net

  lk-jwt-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest
    container_name: lk-jwt-service
    restart: unless-stopped
    depends_on:
      - livekit
    extra_hosts:
      - "${DOMAIN_LIVEKIT}:${EXTERNAL_IP}"
    environment:
      - LIVEKIT_JWT_PORT=8080
      - LIVEKIT_URL=https://${DOMAIN_LIVEKIT}
      - LIVEKIT_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_FULL_ACCESS_HOMESERVERS=${SYNAPSE_SERVER_NAME}
      - LIVEKIT_INSECURE_SKIP_VERIFY_TLS=true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.lk-jwt.rule=Host(`${DOMAIN_LIVEKIT}`)"
      - "traefik.http.routers.lk-jwt.entrypoints=web"
      - "traefik.http.routers.lk-jwt.service=lk-jwt-service"
      - "traefik.http.routers.lk-jwt-secure.rule=Host(`${DOMAIN_LIVEKIT}`)"
      - "traefik.http.routers.lk-jwt-secure.entrypoints=websecure"
      - "traefik.http.routers.lk-jwt-secure.tls=false"
      - "traefik.http.services.lk-jwt-service.loadbalancer.server.port=8080"
    networks:
      - traefik-net

  element-call:
    image: ghcr.io/element-hq/element-call:latest
    container_name: element-call
    restart: unless-stopped
    volumes:
      - ../element-call-config.json:/app/config.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.element-call.rule=Host(`${DOMAIN_CALL}`)"
      - "traefik.http.routers.element-call.entrypoints=web,websecure"
      - "traefik.http.routers.element-call.service=element-call-service"
      - "traefik.http.routers.element-call.tls=false"
      - "traefik.http.services.element-call-service.loadbalancer.server.port=8080"
    networks:
      - traefik-net
